// <auto-generated />
using System;
using DrugSearch.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DrugSearch.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DrugSearch.Models.Drug", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drugs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cb59beb1-735e-4d0c-94e3-1bcd1d33e8ec"),
                            Description = "Paracetamol is a common pain reliever and fever reducer.",
                            Name = "Paracetamol"
                        },
                        new
                        {
                            Id = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            Description = "Ibuprofen is a nonsteroidal anti-inflammatory drug (NSAID) used to relieve pain, reduce inflammation, and lower fever.",
                            Name = "Ibuprofen"
                        },
                        new
                        {
                            Id = new Guid("96861ef9-0127-4357-8bdc-958e8bf25c1c"),
                            Description = "Omeprazole is used to reduce stomach acid production and treat conditions like stomach and esophagus ulcers and acid reflux.",
                            Name = "Omeprazole"
                        },
                        new
                        {
                            Id = new Guid("6dda5905-01de-4fcf-9fad-6d4151df79ad"),
                            Description = "Amoxicillin is an antibiotic used to treat bacterial infections, including respiratory and urinary tract infections.",
                            Name = "Amoxicillin"
                        },
                        new
                        {
                            Id = new Guid("9a03bc77-4857-4afa-bc3d-340afacdf525"),
                            Description = "Simvastatin is a medication that lowers cholesterol levels in the blood, reducing the risk of heart disease.",
                            Name = "Simvastatin"
                        },
                        new
                        {
                            Id = new Guid("396f317e-6b80-489d-aa7c-a7e7a63e2cd1"),
                            Description = "Levothyroxine is used to treat an underactive thyroid gland (hypothyroidism) and maintain normal metabolism.",
                            Name = "Levothyroxine"
                        },
                        new
                        {
                            Id = new Guid("6b658814-9de3-4a35-b75a-4e7578c4ae99"),
                            Description = "Metformin is a drug used to treat type 2 diabetes by lowering blood sugar levels.",
                            Name = "Metformin"
                        },
                        new
                        {
                            Id = new Guid("b11391bd-84fd-4afc-ae7e-bfab9a75965f"),
                            Description = "Lisinopril is an angiotensin-converting enzyme (ACE) inhibitor used to lower high blood pressure and treat heart failure.",
                            Name = "Lisinopril"
                        },
                        new
                        {
                            Id = new Guid("cade813a-ba72-4a30-9348-653a3d731dc4"),
                            Description = "Aspirin is commonly used as a pain reliever and anti-inflammatory agent, as well as for its blood-thinning properties.",
                            Name = "Aspirin"
                        },
                        new
                        {
                            Id = new Guid("da014c12-c152-48f1-bcc2-68e96ed2a284"),
                            Description = "Atorvastatin is a medication used to lower cholesterol levels and reduce the risk of cardiovascular diseases.",
                            Name = "Atorvastatin"
                        },
                        new
                        {
                            Id = new Guid("614cc30c-d136-4350-b66b-9d0e67ca3d4d"),
                            Description = "Albuterol is a bronchodilator used to relieve symptoms of asthma and chronic obstructive pulmonary disease (COPD).",
                            Name = "Albuterol"
                        },
                        new
                        {
                            Id = new Guid("4a67d79a-af3e-4252-bd6d-754664b8246d"),
                            Description = "Prednisone is a corticosteroid medication used to reduce inflammation and suppress the immune system.",
                            Name = "Prednisone"
                        },
                        new
                        {
                            Id = new Guid("5575b1b0-14fc-43a4-bc7c-e18d3ff492f0"),
                            Description = "Ciprofloxacin is an antibiotic used to treat a variety of bacterial infections, including urinary tract and skin infections.",
                            Name = "Ciprofloxacin"
                        },
                        new
                        {
                            Id = new Guid("056a9d5d-a3bc-41c9-9f13-7da629eb2cb1"),
                            Description = "Losartan is an angiotensin II receptor blocker (ARB) used to treat high blood pressure and protect the kidneys in diabetes.",
                            Name = "Losartan"
                        },
                        new
                        {
                            Id = new Guid("e02726a6-2517-4043-b3bd-d0a6324f8b0b"),
                            Description = "Hydrochlorothiazide is a diuretic used to treat high blood pressure and reduce fluid retention.",
                            Name = "Hydrochlorothiazide"
                        },
                        new
                        {
                            Id = new Guid("b39ef71d-f523-4368-b267-6ff4a4b19f70"),
                            Description = "Amlodipine is a calcium channel blocker used to treat high blood pressure and angina (chest pain).",
                            Name = "Amlodipine"
                        },
                        new
                        {
                            Id = new Guid("9cc16471-34d6-46d4-84f0-0bd955067cec"),
                            Description = "Metoprolol is a beta-blocker used to treat high blood pressure and prevent heart attacks and migraines.",
                            Name = "Metoprolol"
                        },
                        new
                        {
                            Id = new Guid("09532631-d42f-4b8e-bd74-9fb8c8b94f3f"),
                            Description = "Warfarin is an anticoagulant (blood thinner) used to prevent blood clots and strokes.",
                            Name = "Warfarin"
                        },
                        new
                        {
                            Id = new Guid("2158eec6-0a03-4921-b7f0-8fd6f11fa1cd"),
                            Description = "Diazepam is a benzodiazepine used to treat anxiety, muscle spasms, and seizures.",
                            Name = "Diazepam"
                        },
                        new
                        {
                            Id = new Guid("6876a1bd-41b8-438d-9e28-d38d59493e74"),
                            Description = "Loratadine is an antihistamine used to relieve allergy symptoms such as sneezing, runny nose, and itching.",
                            Name = "Loratadine"
                        },
                        new
                        {
                            Id = new Guid("62befa9f-8f33-4340-91af-5460b996fe0d"),
                            Description = "Fluoxetine is an antidepressant medication used to treat depression, obsessive-compulsive disorder (OCD), and panic disorder.",
                            Name = "Fluoxetine"
                        },
                        new
                        {
                            Id = new Guid("e2910069-5293-4740-b7ff-e34e69645db4"),
                            Description = "Citalopram is an antidepressant medication used to treat depression and anxiety disorders.",
                            Name = "Citalopram"
                        },
                        new
                        {
                            Id = new Guid("fb9e2de2-5576-4ddb-8150-72cc0201bbb9"),
                            Description = "Venlafaxine is an antidepressant used to treat major depressive disorder and generalized anxiety disorder.",
                            Name = "Venlafaxine"
                        },
                        new
                        {
                            Id = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            Description = "Olanzapine is an antipsychotic medication used to treat schizophrenia and bipolar disorder.",
                            Name = "Olanzapine"
                        },
                        new
                        {
                            Id = new Guid("44662994-9fd9-4835-92ac-41403a6d0c9d"),
                            Description = "Ranitidine is an H2 blocker used to reduce stomach acid and relieve conditions like heartburn and ulcers.",
                            Name = "Ranitidine"
                        },
                        new
                        {
                            Id = new Guid("f3b33f0a-a46b-431b-b4f4-b66b83077049"),
                            Description = "Hydrocodone is an opioid pain medication used to relieve moderate to severe pain.",
                            Name = "Hydrocodone"
                        },
                        new
                        {
                            Id = new Guid("acfdf482-80ac-43e5-bc5c-93f9854fd7e6"),
                            Description = "Tramadol is a synthetic opioid used to treat moderate to severe pain.",
                            Name = "Tramadol"
                        },
                        new
                        {
                            Id = new Guid("642ee04e-a9cf-4bdd-8133-ed5c04506d0d"),
                            Description = "Has a positive effect on brain metabolic processes, increases the concentration of ATP in brain tissue",
                            Name = "Piracetam"
                        });
                });

            modelBuilder.Entity("DrugSearch.Models.DrugPriceInDrugStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DrugId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DrugStoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DrugId");

                    b.HasIndex("DrugStoreId");

                    b.ToTable("DrugPriceInDrugStores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5e11f88-ef6e-46d3-97b6-3551aeae12fa"),
                            DrugId = new Guid("6dda5905-01de-4fcf-9fad-6d4151df79ad"),
                            DrugStoreId = new Guid("57a9cd69-d6d5-48f9-835a-44095282bebc"),
                            Price = "26.75"
                        },
                        new
                        {
                            Id = new Guid("1aca2a3b-3623-4af4-bff7-8a5e19f2e321"),
                            DrugId = new Guid("da014c12-c152-48f1-bcc2-68e96ed2a284"),
                            DrugStoreId = new Guid("57a9cd69-d6d5-48f9-835a-44095282bebc"),
                            Price = "16.87"
                        },
                        new
                        {
                            Id = new Guid("d9214414-2956-4553-a37d-45f6aa24c824"),
                            DrugId = new Guid("da014c12-c152-48f1-bcc2-68e96ed2a284"),
                            DrugStoreId = new Guid("57a9cd69-d6d5-48f9-835a-44095282bebc"),
                            Price = "8.76"
                        },
                        new
                        {
                            Id = new Guid("844ac382-1725-4101-9c2e-46dcd8fdc023"),
                            DrugId = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            DrugStoreId = new Guid("b15eaab4-e9cf-438f-a925-ab648b2d10f8"),
                            Price = "29.23"
                        },
                        new
                        {
                            Id = new Guid("ba2ef979-3a3b-44d2-b739-4c2036534b16"),
                            DrugId = new Guid("614cc30c-d136-4350-b66b-9d0e67ca3d4d"),
                            DrugStoreId = new Guid("b15eaab4-e9cf-438f-a925-ab648b2d10f8"),
                            Price = "14.92"
                        },
                        new
                        {
                            Id = new Guid("ef5cbf89-9ade-4273-9923-b0de28557e8f"),
                            DrugId = new Guid("e2910069-5293-4740-b7ff-e34e69645db4"),
                            DrugStoreId = new Guid("b15eaab4-e9cf-438f-a925-ab648b2d10f8"),
                            Price = "22.99"
                        },
                        new
                        {
                            Id = new Guid("f79bed48-a50f-4d84-b947-99e449caf3f9"),
                            DrugId = new Guid("b39ef71d-f523-4368-b267-6ff4a4b19f70"),
                            DrugStoreId = new Guid("e5f3e4b3-42f4-4cfa-9880-2448bde780c8"),
                            Price = "18.80"
                        },
                        new
                        {
                            Id = new Guid("e9efb5eb-d09f-4953-beb1-4e23da7498e4"),
                            DrugId = new Guid("4a67d79a-af3e-4252-bd6d-754664b8246d"),
                            DrugStoreId = new Guid("e5f3e4b3-42f4-4cfa-9880-2448bde780c8"),
                            Price = "17.52"
                        },
                        new
                        {
                            Id = new Guid("a9db64fd-1a1b-4004-9d6f-b9cba7b6138b"),
                            DrugId = new Guid("acfdf482-80ac-43e5-bc5c-93f9854fd7e6"),
                            DrugStoreId = new Guid("e5f3e4b3-42f4-4cfa-9880-2448bde780c8"),
                            Price = "14.22"
                        },
                        new
                        {
                            Id = new Guid("d559f5aa-e908-418d-b091-78ce4e3ac092"),
                            DrugId = new Guid("cade813a-ba72-4a30-9348-653a3d731dc4"),
                            DrugStoreId = new Guid("5ea71807-f78f-4b19-8ea6-babab2e7781d"),
                            Price = "21.07"
                        },
                        new
                        {
                            Id = new Guid("46427edf-1373-4a2f-b982-51d914d4532b"),
                            DrugId = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            DrugStoreId = new Guid("5ea71807-f78f-4b19-8ea6-babab2e7781d"),
                            Price = "13.79"
                        },
                        new
                        {
                            Id = new Guid("a5978995-a1c1-45f8-976c-0349b334098b"),
                            DrugId = new Guid("614cc30c-d136-4350-b66b-9d0e67ca3d4d"),
                            DrugStoreId = new Guid("5ea71807-f78f-4b19-8ea6-babab2e7781d"),
                            Price = "24.86"
                        },
                        new
                        {
                            Id = new Guid("ea91ef8d-4da6-4640-85ba-3c758b7a2bdd"),
                            DrugId = new Guid("6dda5905-01de-4fcf-9fad-6d4151df79ad"),
                            DrugStoreId = new Guid("21eadb08-69ef-4f82-9771-c9415149c423"),
                            Price = "25.27"
                        },
                        new
                        {
                            Id = new Guid("0f088d08-a155-4852-b3fe-172f760368e5"),
                            DrugId = new Guid("b39ef71d-f523-4368-b267-6ff4a4b19f70"),
                            DrugStoreId = new Guid("21eadb08-69ef-4f82-9771-c9415149c423"),
                            Price = "13.88"
                        },
                        new
                        {
                            Id = new Guid("875f2fc2-da95-4e4c-a1d3-0989f59b3b38"),
                            DrugId = new Guid("62befa9f-8f33-4340-91af-5460b996fe0d"),
                            DrugStoreId = new Guid("21eadb08-69ef-4f82-9771-c9415149c423"),
                            Price = "28.77"
                        },
                        new
                        {
                            Id = new Guid("9ebda6f9-4ae8-4202-91cb-6bb627f95606"),
                            DrugId = new Guid("cb59beb1-735e-4d0c-94e3-1bcd1d33e8ec"),
                            DrugStoreId = new Guid("0316a52a-0705-4032-8668-87a163cd24eb"),
                            Price = "28.79"
                        },
                        new
                        {
                            Id = new Guid("97b60c84-e1fe-4a43-a495-eef876102406"),
                            DrugId = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            DrugStoreId = new Guid("0316a52a-0705-4032-8668-87a163cd24eb"),
                            Price = "5.52"
                        },
                        new
                        {
                            Id = new Guid("33c57d80-3e08-4e85-9667-05a5d9bae391"),
                            DrugId = new Guid("b11391bd-84fd-4afc-ae7e-bfab9a75965f"),
                            DrugStoreId = new Guid("0316a52a-0705-4032-8668-87a163cd24eb"),
                            Price = "29.94"
                        },
                        new
                        {
                            Id = new Guid("3525e67d-0862-485d-8716-0a4d869de805"),
                            DrugId = new Guid("acfdf482-80ac-43e5-bc5c-93f9854fd7e6"),
                            DrugStoreId = new Guid("00a43880-fba6-4bcb-a6bf-b5266cc37cc1"),
                            Price = "29.79"
                        },
                        new
                        {
                            Id = new Guid("64208bd6-5565-4626-b5cb-479a78e3cd68"),
                            DrugId = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            DrugStoreId = new Guid("00a43880-fba6-4bcb-a6bf-b5266cc37cc1"),
                            Price = "24.56"
                        },
                        new
                        {
                            Id = new Guid("18238bdb-81d2-4aea-8e66-cc1c9fab8798"),
                            DrugId = new Guid("62befa9f-8f33-4340-91af-5460b996fe0d"),
                            DrugStoreId = new Guid("00a43880-fba6-4bcb-a6bf-b5266cc37cc1"),
                            Price = "16.42"
                        },
                        new
                        {
                            Id = new Guid("930d976c-9ff4-45b8-a2cc-82cc3d310c45"),
                            DrugId = new Guid("056a9d5d-a3bc-41c9-9f13-7da629eb2cb1"),
                            DrugStoreId = new Guid("19deb140-7279-4ca5-bac3-73145c984eaa"),
                            Price = "22.73"
                        },
                        new
                        {
                            Id = new Guid("0dbb8012-6a4e-467a-9a50-4ff21a14f921"),
                            DrugId = new Guid("96861ef9-0127-4357-8bdc-958e8bf25c1c"),
                            DrugStoreId = new Guid("19deb140-7279-4ca5-bac3-73145c984eaa"),
                            Price = "7.61"
                        },
                        new
                        {
                            Id = new Guid("6ce75acc-204e-4074-be30-a5e04dd961b9"),
                            DrugId = new Guid("642ee04e-a9cf-4bdd-8133-ed5c04506d0d"),
                            DrugStoreId = new Guid("19deb140-7279-4ca5-bac3-73145c984eaa"),
                            Price = "25.10"
                        },
                        new
                        {
                            Id = new Guid("1d398d3a-f9c1-46a9-a719-a53ee4a7fa32"),
                            DrugId = new Guid("e2910069-5293-4740-b7ff-e34e69645db4"),
                            DrugStoreId = new Guid("643581f2-d085-4f62-8a47-baa00b277bd8"),
                            Price = "11.88"
                        },
                        new
                        {
                            Id = new Guid("76fdc025-9cbd-4309-b508-5ce8c0fb11e2"),
                            DrugId = new Guid("5575b1b0-14fc-43a4-bc7c-e18d3ff492f0"),
                            DrugStoreId = new Guid("643581f2-d085-4f62-8a47-baa00b277bd8"),
                            Price = "17.53"
                        },
                        new
                        {
                            Id = new Guid("fe9f8f1c-f4ac-4b20-9eb3-5e142bf5e4cb"),
                            DrugId = new Guid("e2910069-5293-4740-b7ff-e34e69645db4"),
                            DrugStoreId = new Guid("643581f2-d085-4f62-8a47-baa00b277bd8"),
                            Price = "17.71"
                        },
                        new
                        {
                            Id = new Guid("dc8b22ad-5a89-47ac-bf94-470353a3ff31"),
                            DrugId = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            DrugStoreId = new Guid("5a773426-4389-483a-b748-4144532e4913"),
                            Price = "6.25"
                        },
                        new
                        {
                            Id = new Guid("d33402f4-5efe-477f-b972-ab383ccb034a"),
                            DrugId = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            DrugStoreId = new Guid("5a773426-4389-483a-b748-4144532e4913"),
                            Price = "22.96"
                        },
                        new
                        {
                            Id = new Guid("0b7877b0-dc85-4b1f-9a3f-0ff30b5443f5"),
                            DrugId = new Guid("da014c12-c152-48f1-bcc2-68e96ed2a284"),
                            DrugStoreId = new Guid("5a773426-4389-483a-b748-4144532e4913"),
                            Price = "10.06"
                        },
                        new
                        {
                            Id = new Guid("b32590b1-cf79-484a-a417-26b18160f237"),
                            DrugId = new Guid("4a67d79a-af3e-4252-bd6d-754664b8246d"),
                            DrugStoreId = new Guid("b7528e58-a216-4e2f-9077-37bd279278ce"),
                            Price = "21.82"
                        },
                        new
                        {
                            Id = new Guid("8344eaed-32d1-47a3-acd9-11423bd92943"),
                            DrugId = new Guid("642ee04e-a9cf-4bdd-8133-ed5c04506d0d"),
                            DrugStoreId = new Guid("b7528e58-a216-4e2f-9077-37bd279278ce"),
                            Price = "6.49"
                        },
                        new
                        {
                            Id = new Guid("8b209f23-84b0-4a55-a20a-ecc4d6b21ac3"),
                            DrugId = new Guid("44662994-9fd9-4835-92ac-41403a6d0c9d"),
                            DrugStoreId = new Guid("b7528e58-a216-4e2f-9077-37bd279278ce"),
                            Price = "21.47"
                        },
                        new
                        {
                            Id = new Guid("8096be36-b953-4e06-a2b0-955bcb1e617b"),
                            DrugId = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            DrugStoreId = new Guid("4c0f3608-1be9-4ed0-ba9d-20641fcbb490"),
                            Price = "6.66"
                        },
                        new
                        {
                            Id = new Guid("17d1aa38-edbf-4966-b908-8c6410a5d105"),
                            DrugId = new Guid("b11391bd-84fd-4afc-ae7e-bfab9a75965f"),
                            DrugStoreId = new Guid("4c0f3608-1be9-4ed0-ba9d-20641fcbb490"),
                            Price = "20.40"
                        },
                        new
                        {
                            Id = new Guid("708daccc-445b-4d50-a74c-c07426a3fef4"),
                            DrugId = new Guid("f3b33f0a-a46b-431b-b4f4-b66b83077049"),
                            DrugStoreId = new Guid("4c0f3608-1be9-4ed0-ba9d-20641fcbb490"),
                            Price = "22.82"
                        },
                        new
                        {
                            Id = new Guid("3b4ba9b2-3b95-4af9-8bee-89fc93550ab5"),
                            DrugId = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            DrugStoreId = new Guid("796e0970-cac2-4f7d-a04a-1bc961d05a69"),
                            Price = "10.53"
                        },
                        new
                        {
                            Id = new Guid("4f992bd7-9656-4848-9e42-01fa90d366cc"),
                            DrugId = new Guid("b11391bd-84fd-4afc-ae7e-bfab9a75965f"),
                            DrugStoreId = new Guid("796e0970-cac2-4f7d-a04a-1bc961d05a69"),
                            Price = "20.59"
                        },
                        new
                        {
                            Id = new Guid("b298b245-622f-47a4-9f28-fa62947d589f"),
                            DrugId = new Guid("cade813a-ba72-4a30-9348-653a3d731dc4"),
                            DrugStoreId = new Guid("796e0970-cac2-4f7d-a04a-1bc961d05a69"),
                            Price = "15.90"
                        },
                        new
                        {
                            Id = new Guid("a5733622-33cf-408d-a988-72eed7bbc794"),
                            DrugId = new Guid("62befa9f-8f33-4340-91af-5460b996fe0d"),
                            DrugStoreId = new Guid("f3c8caf2-57ab-48d0-889b-88512dc17c63"),
                            Price = "24.98"
                        },
                        new
                        {
                            Id = new Guid("f7f18371-e68c-40e6-a47c-d3bb97c6f976"),
                            DrugId = new Guid("9cc16471-34d6-46d4-84f0-0bd955067cec"),
                            DrugStoreId = new Guid("f3c8caf2-57ab-48d0-889b-88512dc17c63"),
                            Price = "11.10"
                        },
                        new
                        {
                            Id = new Guid("6e0cc39a-8c5a-4754-bd27-53b10502da97"),
                            DrugId = new Guid("5575b1b0-14fc-43a4-bc7c-e18d3ff492f0"),
                            DrugStoreId = new Guid("f3c8caf2-57ab-48d0-889b-88512dc17c63"),
                            Price = "7.25"
                        },
                        new
                        {
                            Id = new Guid("e14713b7-7d0c-45c9-8eda-659f675e4c12"),
                            DrugId = new Guid("b39ef71d-f523-4368-b267-6ff4a4b19f70"),
                            DrugStoreId = new Guid("6c6ed7f9-9339-41b7-abfd-fabaa640b734"),
                            Price = "21.94"
                        },
                        new
                        {
                            Id = new Guid("a81eaa75-8a10-4341-a78a-69bb1e812598"),
                            DrugId = new Guid("9cc16471-34d6-46d4-84f0-0bd955067cec"),
                            DrugStoreId = new Guid("6c6ed7f9-9339-41b7-abfd-fabaa640b734"),
                            Price = "19.85"
                        },
                        new
                        {
                            Id = new Guid("0d7e827d-c0df-4282-a12b-7d4a239810e8"),
                            DrugId = new Guid("642ee04e-a9cf-4bdd-8133-ed5c04506d0d"),
                            DrugStoreId = new Guid("6c6ed7f9-9339-41b7-abfd-fabaa640b734"),
                            Price = "19.64"
                        },
                        new
                        {
                            Id = new Guid("29595e47-7139-4bf6-9b9a-70047617d03f"),
                            DrugId = new Guid("09532631-d42f-4b8e-bd74-9fb8c8b94f3f"),
                            DrugStoreId = new Guid("3a79102b-cb9e-45c0-8877-20c3b6890837"),
                            Price = "12.23"
                        },
                        new
                        {
                            Id = new Guid("9b818068-52a4-4eba-b755-2100f93fd9b8"),
                            DrugId = new Guid("5575b1b0-14fc-43a4-bc7c-e18d3ff492f0"),
                            DrugStoreId = new Guid("3a79102b-cb9e-45c0-8877-20c3b6890837"),
                            Price = "28.00"
                        },
                        new
                        {
                            Id = new Guid("5003b66f-ed62-4db8-a05c-bf23a4801d5b"),
                            DrugId = new Guid("396f317e-6b80-489d-aa7c-a7e7a63e2cd1"),
                            DrugStoreId = new Guid("3a79102b-cb9e-45c0-8877-20c3b6890837"),
                            Price = "27.77"
                        },
                        new
                        {
                            Id = new Guid("162f7ca2-1570-484f-883e-a34c4b2fefd2"),
                            DrugId = new Guid("b11391bd-84fd-4afc-ae7e-bfab9a75965f"),
                            DrugStoreId = new Guid("433c9768-284c-4829-b415-e2c1d0012e3e"),
                            Price = "17.93"
                        },
                        new
                        {
                            Id = new Guid("7ebf8b7b-fa63-41e8-bd82-22d847a73068"),
                            DrugId = new Guid("cb59beb1-735e-4d0c-94e3-1bcd1d33e8ec"),
                            DrugStoreId = new Guid("433c9768-284c-4829-b415-e2c1d0012e3e"),
                            Price = "21.26"
                        },
                        new
                        {
                            Id = new Guid("3730ac58-500e-4518-8abf-fdefc2b1af8a"),
                            DrugId = new Guid("cb59beb1-735e-4d0c-94e3-1bcd1d33e8ec"),
                            DrugStoreId = new Guid("433c9768-284c-4829-b415-e2c1d0012e3e"),
                            Price = "10.16"
                        },
                        new
                        {
                            Id = new Guid("a2287229-b23c-4493-b643-0c1098e0e513"),
                            DrugId = new Guid("6b658814-9de3-4a35-b75a-4e7578c4ae99"),
                            DrugStoreId = new Guid("bebfc552-251d-4cfa-8662-fa491c9bcf03"),
                            Price = "8.68"
                        },
                        new
                        {
                            Id = new Guid("d1ab3619-380a-4272-bb07-aef46a676673"),
                            DrugId = new Guid("cade813a-ba72-4a30-9348-653a3d731dc4"),
                            DrugStoreId = new Guid("bebfc552-251d-4cfa-8662-fa491c9bcf03"),
                            Price = "23.68"
                        },
                        new
                        {
                            Id = new Guid("ae245c83-4861-4eff-8203-5ed552845325"),
                            DrugId = new Guid("cade813a-ba72-4a30-9348-653a3d731dc4"),
                            DrugStoreId = new Guid("bebfc552-251d-4cfa-8662-fa491c9bcf03"),
                            Price = "25.63"
                        },
                        new
                        {
                            Id = new Guid("e564749a-7a26-48f2-9151-7b2f27a2cf1a"),
                            DrugId = new Guid("ff38b942-8e0e-446a-95b9-4ea765ffbe41"),
                            DrugStoreId = new Guid("02bdbad6-270a-4f24-b010-16813b51458e"),
                            Price = "7.03"
                        },
                        new
                        {
                            Id = new Guid("c426b5ad-f99b-481f-9aef-3608006ebba9"),
                            DrugId = new Guid("9cc16471-34d6-46d4-84f0-0bd955067cec"),
                            DrugStoreId = new Guid("02bdbad6-270a-4f24-b010-16813b51458e"),
                            Price = "25.37"
                        },
                        new
                        {
                            Id = new Guid("757baba0-a7aa-465e-b0e1-70ddc543fe0e"),
                            DrugId = new Guid("642ee04e-a9cf-4bdd-8133-ed5c04506d0d"),
                            DrugStoreId = new Guid("02bdbad6-270a-4f24-b010-16813b51458e"),
                            Price = "22.76"
                        },
                        new
                        {
                            Id = new Guid("4434ecee-d588-48df-ab8b-2b0dd9948b05"),
                            DrugId = new Guid("6b658814-9de3-4a35-b75a-4e7578c4ae99"),
                            DrugStoreId = new Guid("9b52f1ea-ca88-4613-b091-961398151380"),
                            Price = "21.01"
                        },
                        new
                        {
                            Id = new Guid("eff2feb1-0879-492c-a5d2-82abb4335a12"),
                            DrugId = new Guid("62befa9f-8f33-4340-91af-5460b996fe0d"),
                            DrugStoreId = new Guid("9b52f1ea-ca88-4613-b091-961398151380"),
                            Price = "23.68"
                        },
                        new
                        {
                            Id = new Guid("4a4af062-d479-44c0-970e-0b518ec30c65"),
                            DrugId = new Guid("44662994-9fd9-4835-92ac-41403a6d0c9d"),
                            DrugStoreId = new Guid("9b52f1ea-ca88-4613-b091-961398151380"),
                            Price = "28.13"
                        },
                        new
                        {
                            Id = new Guid("6d1f3ca4-9377-4fee-8f6a-e429f7fc2367"),
                            DrugId = new Guid("9a03bc77-4857-4afa-bc3d-340afacdf525"),
                            DrugStoreId = new Guid("d2455801-22ba-446a-91fa-f4517cfdb26e"),
                            Price = "22.76"
                        },
                        new
                        {
                            Id = new Guid("8fd931db-bb6c-4d4e-9f41-42f086b22cc3"),
                            DrugId = new Guid("fb9e2de2-5576-4ddb-8150-72cc0201bbb9"),
                            DrugStoreId = new Guid("d2455801-22ba-446a-91fa-f4517cfdb26e"),
                            Price = "12.59"
                        },
                        new
                        {
                            Id = new Guid("f8df53ac-dc7a-4a77-89b0-2c0e951db717"),
                            DrugId = new Guid("fb9e2de2-5576-4ddb-8150-72cc0201bbb9"),
                            DrugStoreId = new Guid("d2455801-22ba-446a-91fa-f4517cfdb26e"),
                            Price = "16.02"
                        },
                        new
                        {
                            Id = new Guid("7ead413c-e7d8-405a-832c-6211e1de8753"),
                            DrugId = new Guid("4a67d79a-af3e-4252-bd6d-754664b8246d"),
                            DrugStoreId = new Guid("cae44210-02f9-441e-b1c0-6bce58fed681"),
                            Price = "6.83"
                        },
                        new
                        {
                            Id = new Guid("ee7f00ca-03f4-4636-8396-155515272e1a"),
                            DrugId = new Guid("e02726a6-2517-4043-b3bd-d0a6324f8b0b"),
                            DrugStoreId = new Guid("cae44210-02f9-441e-b1c0-6bce58fed681"),
                            Price = "26.71"
                        },
                        new
                        {
                            Id = new Guid("a72a8b64-559a-4bb9-a19e-53dba69d2298"),
                            DrugId = new Guid("f3b33f0a-a46b-431b-b4f4-b66b83077049"),
                            DrugStoreId = new Guid("cae44210-02f9-441e-b1c0-6bce58fed681"),
                            Price = "21.17"
                        },
                        new
                        {
                            Id = new Guid("ef66cae1-85b2-40c3-ba9b-ef91bdd54d27"),
                            DrugId = new Guid("9a03bc77-4857-4afa-bc3d-340afacdf525"),
                            DrugStoreId = new Guid("5eafb1b6-86b0-4647-9b77-a43cc5e9aea5"),
                            Price = "9.60"
                        },
                        new
                        {
                            Id = new Guid("0a806e88-34ca-430f-a7af-37c274713f5b"),
                            DrugId = new Guid("e2910069-5293-4740-b7ff-e34e69645db4"),
                            DrugStoreId = new Guid("5eafb1b6-86b0-4647-9b77-a43cc5e9aea5"),
                            Price = "12.36"
                        },
                        new
                        {
                            Id = new Guid("44e34f4f-8c00-45d9-8dbf-ba3039635045"),
                            DrugId = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            DrugStoreId = new Guid("5eafb1b6-86b0-4647-9b77-a43cc5e9aea5"),
                            Price = "14.06"
                        },
                        new
                        {
                            Id = new Guid("ff60fde6-3b1d-4962-a631-c038f7a91ce2"),
                            DrugId = new Guid("614cc30c-d136-4350-b66b-9d0e67ca3d4d"),
                            DrugStoreId = new Guid("da03d3fb-54f0-4a7a-acec-c9e5ded9fc9c"),
                            Price = "11.37"
                        },
                        new
                        {
                            Id = new Guid("ec30762b-23b1-43ed-bb4b-861478f539a2"),
                            DrugId = new Guid("f3b33f0a-a46b-431b-b4f4-b66b83077049"),
                            DrugStoreId = new Guid("da03d3fb-54f0-4a7a-acec-c9e5ded9fc9c"),
                            Price = "27.79"
                        },
                        new
                        {
                            Id = new Guid("2b3ee27c-f7a1-48fd-a4f0-23a19779262b"),
                            DrugId = new Guid("09532631-d42f-4b8e-bd74-9fb8c8b94f3f"),
                            DrugStoreId = new Guid("da03d3fb-54f0-4a7a-acec-c9e5ded9fc9c"),
                            Price = "14.00"
                        },
                        new
                        {
                            Id = new Guid("7a9a4b18-3737-4347-87bd-9d04861b6973"),
                            DrugId = new Guid("acfdf482-80ac-43e5-bc5c-93f9854fd7e6"),
                            DrugStoreId = new Guid("03b4ea4d-fdb7-4fd6-8712-e9f0e6e6b44a"),
                            Price = "15.08"
                        },
                        new
                        {
                            Id = new Guid("1f2b9799-7843-47d8-847a-eba01242e437"),
                            DrugId = new Guid("614cc30c-d136-4350-b66b-9d0e67ca3d4d"),
                            DrugStoreId = new Guid("03b4ea4d-fdb7-4fd6-8712-e9f0e6e6b44a"),
                            Price = "8.67"
                        },
                        new
                        {
                            Id = new Guid("6de6ef74-1b66-4d46-9c0a-e8bfa8453331"),
                            DrugId = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            DrugStoreId = new Guid("03b4ea4d-fdb7-4fd6-8712-e9f0e6e6b44a"),
                            Price = "13.58"
                        },
                        new
                        {
                            Id = new Guid("c97eea41-aeaf-48f2-8a76-e66bd64478a3"),
                            DrugId = new Guid("96861ef9-0127-4357-8bdc-958e8bf25c1c"),
                            DrugStoreId = new Guid("862a3b4f-5ceb-4895-97bb-7919a1d1f40d"),
                            Price = "6.94"
                        },
                        new
                        {
                            Id = new Guid("65f80904-326a-4c24-b13c-47aa9099b001"),
                            DrugId = new Guid("056a9d5d-a3bc-41c9-9f13-7da629eb2cb1"),
                            DrugStoreId = new Guid("862a3b4f-5ceb-4895-97bb-7919a1d1f40d"),
                            Price = "23.26"
                        },
                        new
                        {
                            Id = new Guid("e5bec5e1-ed7f-4700-8616-5e3d7d91f20e"),
                            DrugId = new Guid("2158eec6-0a03-4921-b7f0-8fd6f11fa1cd"),
                            DrugStoreId = new Guid("862a3b4f-5ceb-4895-97bb-7919a1d1f40d"),
                            Price = "26.54"
                        },
                        new
                        {
                            Id = new Guid("c51fcba5-46b4-4d5f-ae57-79bf9db03f8d"),
                            DrugId = new Guid("acfdf482-80ac-43e5-bc5c-93f9854fd7e6"),
                            DrugStoreId = new Guid("7d9c34f7-2003-4b15-8200-b40dd9672678"),
                            Price = "16.36"
                        },
                        new
                        {
                            Id = new Guid("1c3f30ce-5f32-48d3-b13b-908cb45234c9"),
                            DrugId = new Guid("642ee04e-a9cf-4bdd-8133-ed5c04506d0d"),
                            DrugStoreId = new Guid("7d9c34f7-2003-4b15-8200-b40dd9672678"),
                            Price = "8.86"
                        },
                        new
                        {
                            Id = new Guid("9b4a54cf-a252-46b7-b83e-dd3bf4635b11"),
                            DrugId = new Guid("e2910069-5293-4740-b7ff-e34e69645db4"),
                            DrugStoreId = new Guid("7d9c34f7-2003-4b15-8200-b40dd9672678"),
                            Price = "15.92"
                        },
                        new
                        {
                            Id = new Guid("44fb2e35-7608-4448-bccb-df0030fc3d82"),
                            DrugId = new Guid("b11391bd-84fd-4afc-ae7e-bfab9a75965f"),
                            DrugStoreId = new Guid("60e1cfe3-c98b-42d1-a209-92465012d3bc"),
                            Price = "15.29"
                        },
                        new
                        {
                            Id = new Guid("cedacbe7-f9f6-4c7e-b414-81a23798fc94"),
                            DrugId = new Guid("b39ef71d-f523-4368-b267-6ff4a4b19f70"),
                            DrugStoreId = new Guid("60e1cfe3-c98b-42d1-a209-92465012d3bc"),
                            Price = "19.54"
                        },
                        new
                        {
                            Id = new Guid("4ff2e184-20bd-4fa6-9a65-dbb0bd78737a"),
                            DrugId = new Guid("9b8d3ac5-d3b1-43f1-a78b-28838fd6de73"),
                            DrugStoreId = new Guid("60e1cfe3-c98b-42d1-a209-92465012d3bc"),
                            Price = "7.66"
                        },
                        new
                        {
                            Id = new Guid("bebe1ecc-28fd-4ab3-a40a-d57a82b71243"),
                            DrugId = new Guid("6b658814-9de3-4a35-b75a-4e7578c4ae99"),
                            DrugStoreId = new Guid("fc9ab48d-2a34-45ad-858b-dc8875a2b7b6"),
                            Price = "20.47"
                        },
                        new
                        {
                            Id = new Guid("f0b3d2bb-0529-4096-a88a-6105374a79db"),
                            DrugId = new Guid("44662994-9fd9-4835-92ac-41403a6d0c9d"),
                            DrugStoreId = new Guid("fc9ab48d-2a34-45ad-858b-dc8875a2b7b6"),
                            Price = "14.46"
                        },
                        new
                        {
                            Id = new Guid("4dbd2104-7a42-477b-81a8-3eb7d1aae05f"),
                            DrugId = new Guid("cb59beb1-735e-4d0c-94e3-1bcd1d33e8ec"),
                            DrugStoreId = new Guid("fc9ab48d-2a34-45ad-858b-dc8875a2b7b6"),
                            Price = "28.96"
                        },
                        new
                        {
                            Id = new Guid("89e6e2f6-3898-4e07-8e10-6bc8d461bb7a"),
                            DrugId = new Guid("acfdf482-80ac-43e5-bc5c-93f9854fd7e6"),
                            DrugStoreId = new Guid("a14244f9-4bc6-413b-8503-01bc9e5078cd"),
                            Price = "14.07"
                        },
                        new
                        {
                            Id = new Guid("e594f847-2731-45c6-a8e8-d815273a221a"),
                            DrugId = new Guid("b39ef71d-f523-4368-b267-6ff4a4b19f70"),
                            DrugStoreId = new Guid("a14244f9-4bc6-413b-8503-01bc9e5078cd"),
                            Price = "13.84"
                        },
                        new
                        {
                            Id = new Guid("aa830359-4125-4e5e-88e1-ba5199122006"),
                            DrugId = new Guid("9a03bc77-4857-4afa-bc3d-340afacdf525"),
                            DrugStoreId = new Guid("a14244f9-4bc6-413b-8503-01bc9e5078cd"),
                            Price = "21.99"
                        });
                });

            modelBuilder.Entity("DrugSearch.Models.DrugStore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DrugStores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57a9cd69-d6d5-48f9-835a-44095282bebc"),
                            Address = "East Scarlett:98921 Schowalter Walk",
                            Contacts = "1-286-744-1088 x168",
                            Name = "Murazik - Kohler"
                        },
                        new
                        {
                            Id = new Guid("b15eaab4-e9cf-438f-a925-ab648b2d10f8"),
                            Address = "South Nellaville:1381 Roosevelt Prairie",
                            Contacts = "215.736.2362",
                            Name = "Cremin Group"
                        },
                        new
                        {
                            Id = new Guid("e5f3e4b3-42f4-4cfa-9880-2448bde780c8"),
                            Address = "Port Wilsonfort:107 Horace Turnpike",
                            Contacts = "784.894.8140",
                            Name = "Botsford Inc"
                        },
                        new
                        {
                            Id = new Guid("5ea71807-f78f-4b19-8ea6-babab2e7781d"),
                            Address = "West Jeanside:784 Heaney Land",
                            Contacts = "1-883-731-3046 x03725",
                            Name = "Ritchie, Bahringer and Hegmann"
                        },
                        new
                        {
                            Id = new Guid("21eadb08-69ef-4f82-9771-c9415149c423"),
                            Address = "Nicolasview:403 Claud Land",
                            Contacts = "482.815.2507 x93736",
                            Name = "Hodkiewicz LLC"
                        },
                        new
                        {
                            Id = new Guid("0316a52a-0705-4032-8668-87a163cd24eb"),
                            Address = "Lake Biankatown:465 Quigley Haven",
                            Contacts = "(676) 256-7187",
                            Name = "McKenzie LLC"
                        },
                        new
                        {
                            Id = new Guid("00a43880-fba6-4bcb-a6bf-b5266cc37cc1"),
                            Address = "Justynfort:03722 Waelchi Square",
                            Contacts = "915.731.6722 x9769",
                            Name = "D'Amore, Schmitt and Cremin"
                        },
                        new
                        {
                            Id = new Guid("19deb140-7279-4ca5-bac3-73145c984eaa"),
                            Address = "Reillyberg:059 Tanya Shoal",
                            Contacts = "(304) 525-9436 x77433",
                            Name = "White - Cruickshank"
                        },
                        new
                        {
                            Id = new Guid("643581f2-d085-4f62-8a47-baa00b277bd8"),
                            Address = "Huelfort:0194 Terry Canyon",
                            Contacts = "(993) 484-2981",
                            Name = "Haley - Breitenberg"
                        },
                        new
                        {
                            Id = new Guid("5a773426-4389-483a-b748-4144532e4913"),
                            Address = "Mikeborough:7443 Margot Row",
                            Contacts = "666.362.5412 x54257",
                            Name = "Corkery LLC"
                        },
                        new
                        {
                            Id = new Guid("b7528e58-a216-4e2f-9077-37bd279278ce"),
                            Address = "Morganmouth:075 Dicki Way",
                            Contacts = "270-887-1926 x1787",
                            Name = "Hansen Group"
                        },
                        new
                        {
                            Id = new Guid("4c0f3608-1be9-4ed0-ba9d-20641fcbb490"),
                            Address = "New Milford:6814 Deshawn Ramp",
                            Contacts = "(569) 978-6169 x594",
                            Name = "McClure, Pfannerstill and Gulgowski"
                        },
                        new
                        {
                            Id = new Guid("796e0970-cac2-4f7d-a04a-1bc961d05a69"),
                            Address = "Handstad:63209 Jacques Views",
                            Contacts = "(847) 677-7128",
                            Name = "Jacobi, Ortiz and Barrows"
                        },
                        new
                        {
                            Id = new Guid("f3c8caf2-57ab-48d0-889b-88512dc17c63"),
                            Address = "Harrismouth:3526 Justine Crossroad",
                            Contacts = "1-632-825-8400 x1687",
                            Name = "Ondricka - Bashirian"
                        },
                        new
                        {
                            Id = new Guid("6c6ed7f9-9339-41b7-abfd-fabaa640b734"),
                            Address = "Port Henryberg:06592 Dare Throughway",
                            Contacts = "802-465-8816",
                            Name = "Hayes - Bartell"
                        },
                        new
                        {
                            Id = new Guid("3a79102b-cb9e-45c0-8877-20c3b6890837"),
                            Address = "Port Khalilton:95007 Judah Cove",
                            Contacts = "1-309-782-4070",
                            Name = "D'Amore - Mertz"
                        },
                        new
                        {
                            Id = new Guid("433c9768-284c-4829-b415-e2c1d0012e3e"),
                            Address = "Lake Otho:377 Kailee Trace",
                            Contacts = "326-657-0416 x42908",
                            Name = "Champlin, Labadie and Windler"
                        },
                        new
                        {
                            Id = new Guid("bebfc552-251d-4cfa-8662-fa491c9bcf03"),
                            Address = "East Everettburgh:3378 Roob Fords",
                            Contacts = "1-204-927-7758 x8134",
                            Name = "Mante, Gleason and Towne"
                        },
                        new
                        {
                            Id = new Guid("02bdbad6-270a-4f24-b010-16813b51458e"),
                            Address = "Williamsonhaven:53793 Conn Shoal",
                            Contacts = "514.580.0098 x7000",
                            Name = "Barton and Sons"
                        },
                        new
                        {
                            Id = new Guid("9b52f1ea-ca88-4613-b091-961398151380"),
                            Address = "Mariahtown:505 Kirlin Stravenue",
                            Contacts = "463-866-7649 x8043",
                            Name = "Wintheiser, Kub and Moore"
                        },
                        new
                        {
                            Id = new Guid("d2455801-22ba-446a-91fa-f4517cfdb26e"),
                            Address = "North Rosemarieton:84495 Shaina Island",
                            Contacts = "906.950.0805 x62176",
                            Name = "Langworth - Bashirian"
                        },
                        new
                        {
                            Id = new Guid("cae44210-02f9-441e-b1c0-6bce58fed681"),
                            Address = "Stoltenbergland:71387 Hamill Coves",
                            Contacts = "220-426-1990",
                            Name = "Stoltenberg Inc"
                        },
                        new
                        {
                            Id = new Guid("5eafb1b6-86b0-4647-9b77-a43cc5e9aea5"),
                            Address = "East Emmaleefurt:2164 Greenfelder Station",
                            Contacts = "571-655-7024 x4302",
                            Name = "Tromp Group"
                        },
                        new
                        {
                            Id = new Guid("da03d3fb-54f0-4a7a-acec-c9e5ded9fc9c"),
                            Address = "Angelaville:5596 Deron Forks",
                            Contacts = "1-359-699-6608",
                            Name = "McDermott LLC"
                        },
                        new
                        {
                            Id = new Guid("03b4ea4d-fdb7-4fd6-8712-e9f0e6e6b44a"),
                            Address = "North Molly:5556 Welch Cliffs",
                            Contacts = "(946) 343-5131 x584",
                            Name = "Hegmann - Turner"
                        },
                        new
                        {
                            Id = new Guid("862a3b4f-5ceb-4895-97bb-7919a1d1f40d"),
                            Address = "South Ceceliabury:63349 Gulgowski Gardens",
                            Contacts = "593-896-9427",
                            Name = "Gerhold, Mills and Lowe"
                        },
                        new
                        {
                            Id = new Guid("7d9c34f7-2003-4b15-8200-b40dd9672678"),
                            Address = "Lake Casimirfurt:80581 Clifton Fords",
                            Contacts = "989-587-3252",
                            Name = "Harris - Hermiston"
                        },
                        new
                        {
                            Id = new Guid("60e1cfe3-c98b-42d1-a209-92465012d3bc"),
                            Address = "Port Yolandafurt:07013 Ankunding Lake",
                            Contacts = "(349) 556-2220",
                            Name = "Cronin - Cummerata"
                        },
                        new
                        {
                            Id = new Guid("fc9ab48d-2a34-45ad-858b-dc8875a2b7b6"),
                            Address = "Christophechester:33390 Von Via",
                            Contacts = "778.727.4032 x2435",
                            Name = "Carter, Schiller and Green"
                        },
                        new
                        {
                            Id = new Guid("a14244f9-4bc6-413b-8503-01bc9e5078cd"),
                            Address = "East Isom:370 Krajcik Viaduct",
                            Contacts = "(749) 823-5507",
                            Name = "Schimmel, Abbott and Rice"
                        });
                });

            modelBuilder.Entity("DrugSearch.Models.DrugPriceInDrugStore", b =>
                {
                    b.HasOne("DrugSearch.Models.Drug", "Drug")
                        .WithMany("PricesInDrugStores")
                        .HasForeignKey("DrugId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrugSearch.Models.DrugStore", "DrugStore")
                        .WithMany("PricesForDrugs")
                        .HasForeignKey("DrugStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Drug");

                    b.Navigation("DrugStore");
                });

            modelBuilder.Entity("DrugSearch.Models.Drug", b =>
                {
                    b.Navigation("PricesInDrugStores");
                });

            modelBuilder.Entity("DrugSearch.Models.DrugStore", b =>
                {
                    b.Navigation("PricesForDrugs");
                });
#pragma warning restore 612, 618
        }
    }
}
